dna='ACGGTCAATTCGAACTACTGGCAGAACGTGCAGAAAGGCGCGAAGGCGGCGCTCGACGGCGCGAAGGGCTACACGATGACGTTCCAGGGCCCGGCGGCCGAGTCCGACATCAGCGGCCAGGTCAACATGGTCGACAACGCGGTCACGCGGCATGTGGCGGGCATCGTGCTCGCGCCGTCCGATCCCGATGCGCTGGTGCCCGCGATCAAGAAGGCGTGGGAAGCGCACATTCCCGTCGTGCTGATCGACTCGGCGATCGCGGACGCCGGCAAGCCGTACTACCAGGCGTTCCTGTCGACCGACAACGAGAAGGCGGGCGCGCTGTGCGCGAAGGCGCTGATCGACCGCGTCGGGCAGTCGGGCAAGATCGCGATCATGTCGTACGTGCCGGGCGCGGGGTCCGAGGTCAGCCGCGTCGGCGGGTTCCGCAAGTACATCGAGAGCCATTCGAAGCTGCAGGTCGTCGGCCCGTACTACTCGCAATCGCAAATGGCGACCGCGCTGAACCAGACGACCGACGTGCTGTCGGCGAACCCGGACCTGAAGGGCATCTTCGGCGCGAACGAGCCGACCGCGGTCGGGATGGGCCGTGCGCTGAAGCAGTCGGGCAAGGCGGGCAAGGTGGTGGCGATCGGGTTCGACGGCAACGAGGACCTGCAGGGCTTCGTGCGCGACGGCACCGTGCAGGCGATCGCCGTGCAGGGCTCGTGGCAGATGGGGAACCAGGGCGTGCGCACGGCGCTCGACGTGATCGAGCGCAAGCCCGCGCCGAAGCTGATCGATACCGGCGTCGTGATGGTCGACAAGCAGAACCTCGATTCGCAGGCGGCGAAGAACGTCCTGTACTGATCCCTTTTCCCCGCATCCGGTTACGCCTCATGAATGCAAACGATACGCGCACCTTGCCGCGCAGCGGGCTGACGGTGTCCGCGCTCGGCCTCGGCTGCTCGCAGCTCGGCGGCCTTTATCGGCCGATGTCGGCCGCCGATGCCGCCGCGCTCGTCGACGCCGCGTGGGCGGCCGGCCTGCGCTATTTCGACACCGCGCCGTATTACGGCTACACGCTGTCCGAGCGGCGCGTGGGGGCGGGGCTCGCCCCGCGCGAGCGCCGCGCCTTCACGCTCAGCACGAAGGTCGGGCGGCTGATGCGGGCCGACGCGAGCGTGCGGCCGGGCGACGACGGCTGGGCGGAGCCGCTGCCGTTCCGGCCGGTGTACGACTACAGCTACGACGGCATCATGCGCTCGCACGACGACAGCCGGCAACGGCTCGGGCTCGCGCGAGTCGACATGCTGTACGTGCACGACATCGGCGCGATGACGCACGGCGATCGTCACGCGCACTACTGGGACCAGTTGACCCGCGGCGGCGGGTTTCGCGCGCTGGATGCGTTGCGCTCGGGCGGCGAGATCGGCGGGTTCGGTCTCGGCGTGAACGAATGGGAAGTCGCGGCCGACGCGCTGAACGAAGCGGCGCTCGATGCGGTGCTGCTGGCCGGCCGCTATACGCTGCTCGAACAGACGGCGCTCGAACCGCTGCTCGACGCGTGTGCCCGTGAAGGGACGGCGATCGTGATCGGCGGCGTGTTCAATTCCGGTTTGCTCGCCGGCAACGGCAAATTCAACTATGCGGACGCGAGCGCCGACGTGATCGACAAGGCGACGCGGCTCGGCGCGTTGTGCAACCGCTTCGACGTGCCGCTTCCGGCCGCGGCGTTGCAGTTTCCGTTCGGCCATCCGGCCGTCGTGTCGTGCGTGGTCGGCGCGCGCAGCGTGGCTCAGCTGAAGCAGAACATCGCATGGTTCGAGCGCCCCGCGCCGGCCGAGCTGTGGGATGCGCTGCGCGACGAAGGGCTGATCGCGGCGCACGCGCCGGTGCCGGGAGCACACGCATGACCCCGCGCATCGACGCCCATCAGCACTACTGGCGCATCGACGCGCGGGCCGGCTGCTGGCCGCCGGCCGAGCTCGACGCGATTCACCGGGATTTCGGCCCGGCCGATCTGGCGCCGCTGCTCGACGCCGCGCGCATCGATATCACCGTCGTCGTGCAGTCGCTGCCGAGCGAAGCCGACACGCGCTTTCTGCTCGATCTCGCGGCTGAAACGCCGAGCGTCGGCGCCGTGGTCGGCTGGGTCGACCTGAAGGCCGACGACGCACCCGCGCGGATCGCGGCGTTTGCATCCGCGCCGAAGGCGCGCGGCTTGCGACCGATGCTGCAGGATCTGCCCGACGACGCGTGGATCGACGATCCGCGGCTGGATCGCGCAGTCGCCGCGATGCTCGAGTACGGGCTGCGTTTCGATGCGCTGGTGATGCCGCGCCATCTCGATGCGCTGCACGCGTTCGCGCAACGCCATCCGGATCTGCCGATCGTGATCGACCACGGCGCGAAGCCGTTCATCGAGCGCGGCGAGATGCAGCCGTGGCTAACGGCGATGCGCAGGCTCGCGAGCCTGCCGAACCTGCATTGCAAGCTGTCCGGCCTCTGGACGGAAGCCGGGCCGTCGGCCGGCCCGGATGCGGTGCGCGCACGCACGCGGCCGTATGTCCAGGCGCTGGCCGAGCTGTTCGGGCCGACGCGCTTGATGTGGGGCAGCGACTGGCCGGTGCTGCGGCTGGCGTCGGCGTGCGGCGGCTACGGCGAATGGCTGGCCGCGTGCGAGGACGACTGCGCGCAGATGCTCGGCGCCGCGGCGCTGGAGGACCTTTTCGGCGGCAACGCGCGCCGCTTCTACCGGATCGACACCGCACGCCACGACGAATGAACCAGAACGAAAGGAAACCGACATGCTCAGCGTGATTTGCGAATCCCCCGGCGTGCTGCGCGTGCAGCATCGCGAGCTGCCCGTGCGCGGCAGCGGCGAAGTGCTGTTGCGCGTGCAACGGGTCGGCATCTGCGGCACCGATCTGCACATCTTCACCGGCAACCAGCCGTACCTCGACTATCCGCGCGTGATGGGCCACGAGCTGTCGGCGGTCGTCGTCGAGGCGGAAGCCGAGTCGGGGCTCGGCGCCGGCGACGCGGTGTACGTGATGCCGTATCTGTCGTGCGGGCACTGCGTCGCCTGCCGTCACGGCAACACGAACTGCTGCGTGAACATCAAGGTGCTCGGCGTGCATCGCGACGGCGCACTCGCCGAATACCTGAGCGTGCCCGCGCAGTTCGTGCACAAGGCCGACGGCATTTCGCTCGACCAGGCGGCGATGCTCGAATTTCTCGCGATCGGCGCGCATGCGGTGCGGCGCGCGGACATCCGCGCCGGGCAGCGCGCGCTGGTCGTCGGCGCCGGGCCGATCGGCATGGCCGCGATGATCTTCGCGAAGCTGCGCGGCGCCGACGTCACGTGCCTCGACACGCGGGCCGACCGGCTGGCGTTCTGCCGCCAGCATCTGGCGGTCGATGCGGCGGTGGAGGTGGGGGAAGGCGACGCGGAGCGTCTCGCGTCGTTGACGAACGGCGAGTATTTCGATGCGGTGTTCGACGCGACCGGCAACCTCGATGCGATGAATCGCGGTTTCGAATTCGTCGCGCACGGCGGCAAATACACGTTGATCTCGATCGTGCGCGGGCACGTCGCGTTTTCGGATCCCGAGTTCCACAAGCGGGAAACCACGCTGCTCGCGAGCCGCAATGCGACGGCCGAGGATTTCGCGACGGTGCTCGACGCGATGCGCGCGGGGCGCATTCCGGACCGCGCGCTGAACACGCACCGGATGCGGCTCGATGAGGTGCCGGACGCGCTGCCGCGTCTGCTGGATGCCGGGCAGACCGTCGTGAAGGCGCTCGTCGAATGCTGATCTATCGAATCCGCCACGCGGAGCGCACGCGATGACGCCGCCGATCCTGCAGTTCGGCACGAGCCGCTTCCTGCTCGCGCACGTCGACCTGTTCGTCTCCCAGGCGCTGGACGAAGGCAACGCGATCGGCGGCATCGGCATCGTGCAGACGACCGGCAATCCGGCCAGCCGCGCCCGCATCGACGCGCTGCGCGCCACCGGCCGCTATCCGGTGCGGATTCGCGGGCGCGAGCGCGGCGGCGTGGTCGACGAAGTCGTCGAGTGCCGCGCCGTGCAGCGCGCGTGGGACGCCGAGCGCGACTGGGCGGAAATACGCGGCGCCGCGATCGAGACGGTGCGCGTGATCGTGTCGAACACCGGCGACGCAGGCTATCGCGCCGATCCGCGCGACGCCGCAAAC'



genetic_code= {
    'ATA':'I', 'ATC':'I', 'ATT':'I', 'ATG':'M',
    'ACA':'T', 'ACC':'T', 'ACG':'T', 'ACT':'T',
    'AAC':'N', 'AAT':'N', 'AAA':'K', 'AAG':'K',
    'AGC':'S', 'AGT':'S', 'AGA':'R', 'AGG':'R',
    'CTA':'L', 'CTC':'L', 'CTG':'L', 'CTT':'L',
    'CCA':'P', 'CCC':'P', 'CCG':'P', 'CCT':'P',
    'CAC':'H', 'CAT':'H', 'CAA':'Q', 'CAG':'Q',
    'CGA':'R', 'CGC':'R', 'CGG':'R', 'CGT':'R',
    'GTA':'V', 'GTC':'V', 'GTG':'V', 'GTT':'V',
    'GCA':'A', 'GCC':'A', 'GCG':'A', 'GCT':'A',
    'GAC':'D', 'GAT':'D', 'GAA':'E', 'GAG':'E',
    'GGA':'G', 'GGC':'G', 'GGG':'G', 'GGT':'G',
    'TCA':'S', 'TCC':'S', 'TCG':'S', 'TCT':'S',
    'TTC':'F', 'TTT':'F', 'TTA':'L', 'TTG':'L',
    'TAC':'Y', 'TAT':'Y', 'TAA':'*', 'TAG':'*',
    'TGC':'C', 'TGT':'C', 'TGA':'*', 'TGG':'W',}


from itertools import takewhile
from Bio import SeqIO
def translate_dna(sequence, genetic_code, stop_codons = ('TAA', 'TGA', 'TAG')):       
    for frame in range (3): 
    	start = sequence[frame:]
    	trimmed_sequence = sequence[start:]
    	codon = str(trimmed_sequence[i:i+3] for i in range(0, len(trimmed_sequence), 3))
    	startcodon= codon.find('ATG')
    	codons= codon[startcodon:]
    	# Take all codons until first stop codon
    	coding_sequence  =  takewhile(lambda x: x not in stop_codons and len(x) == 3 , codons)
    	protein_sequence = ''.join([genetic_code[codon] for codon in coding_sequence])
    	print len(protein_sequence)*3, frame


for record in SeqIO.parse("dna1.fasta.fasta", "fasta"):
		orf_list = translate_dna(record.seq, genetic_code)    
	